In [1]:
import pandas as pd
import os

In [3]:
test_path = "/data/processed/strategy_b/test.csv"

print("File exists:", os.path.exists(test_path))

File exists: True

In [4]:
test_df = pd.read_csv(test_path)

print("Shape:", test_df.shape)
print("Columns:", test_df.columns.tolist())
print("\nLabel distribution:")
print(test_df["label"].value_counts().sort_index())

test_df.head(3)

Shape: (1447, 8)
Columns: ['input_text', 'label', 'Score', 'soru', 'context', 'cevap', 'kaynak', 'veri türü']

Label distribution:
label
0    885
1    562
Name: count, dtype: int64

,input_text,label,Score,soru,context,cevap,kaynak,veri türü
0,Soru: Türklerin dünya tarihine olan etkisi han...,0,8,Türklerin dünya tarihine olan etkisi hangi ala...,"İlk ve Orta Çağlarda Türk dünyası, Türklerin t...","Türklerin dünya tarihine olan etkisi siyasi, a...",OGM Konu Ozetleri,egitim
1,Soru: Eğitim bakanlığının teşkilat ve görevler...,1,9,Eğitim bakanlığının teşkilat ve görevleri hakk...,Türk Millî Eğitim Sisteminin Yasal Çerçevesi \...,"Bu kanun, Bakanlığın teşkilat yapısını, görevl...",TÜRK EĞİTİM SİSTEMİ VE ORTAÖĞRETİM,eğitim
2,"Soru: Bir öğrenci, derslerin ötesinde kendini ...",1,9,"Bir öğrenci, derslerin ötesinde kendini nasıl ...",İyi Bir Öğrenci Olmanın Temel İlkeleri\r\nİyi ...,"Bir öğrenci, derslerin ötesinde kendini gelişt...",https://www.wikihow.com.tr/Çok-İyi-Bir-Öğrenci...,egitim

In [5]:
# Her sınıftan 10 örnek alıyoruz
sample_label_0 = test_df[test_df["label"] == 0].sample(n=10, random_state=42)
sample_label_1 = test_df[test_df["label"] == 1].sample(n=10, random_state=42)

zero_shot_sample = pd.concat([sample_label_0, sample_label_1])
zero_shot_sample = zero_shot_sample.sample(frac=1, random_state=42).reset_index(drop=True)

print("Sample shape:", zero_shot_sample.shape)
print("Sample label distribution:")
print(zero_shot_sample["label"].value_counts().sort_index())

zero_shot_sample[["label", "Score", "soru", "cevap"]].head()

Sample shape: (20, 8)
Sample label distribution:
label
0    10
1    10
Name: count, dtype: int64

,label,Score,soru,cevap
0,0,8,Dünya'nın günlük hareketi ile ilgili başka han...,"Dünya'nın günlük hareketi, Dünya'nın manyetik ..."
1,1,10,Yeni öğretim programlarında hangi konular için...,Yeni öğretim programlarında her konu için ayrı...
2,1,9,Atmosferdeki su buharı miktarındaki artışın Dü...,"Atmosferdeki su buharı miktarındaki artış, kür..."
3,0,8,"Yerleşmenin yükselti sınırı, hangi faktöre bağ...","Yerleşmenin yükselti sınırı, ekvatordan kutupl..."
4,0,8,İnsan ihtiyaçlarını karşılamak için doğayı nas...,"İnsanlar beslenme, barınma, enerji ve hammadde..."

In [6]:
def create_zero_shot_prompt(input_text):
    prompt = f"""
You are evaluating the quality of a Turkish open-ended student answer.

Your task is to classify the answer into one of two labels:

0 = low quality answer
1 = high quality answer

Consider whether the answer is relevant to the question, consistent with the context, and sufficiently explanatory.

Return only one number: 0 or 1.

Input:
{input_text}

Label:
"""
    return prompt.strip()

In [7]:
example_prompt = create_zero_shot_prompt(zero_shot_sample.iloc[0]["input_text"])

print(example_prompt[:3000])
print("\n--- TRUE LABEL:", zero_shot_sample.iloc[0]["label"])

You are evaluating the quality of a Turkish open-ended student answer.

Your task is to classify the answer into one of two labels:

0 = low quality answer
1 = high quality answer

Consider whether the answer is relevant to the question, consistent with the context, and sufficiently explanatory.

Return only one number: 0 or 1.

Input:
Soru: Dünya'nın günlük hareketi ile ilgili başka hangi sonuçlar vardır?
Bağlam: Dünya’nın Günlük (Eksen) Hareketi
Dünya, kuzey ve güney kutup noktalarından geçtiği varsayılan yer ekseni etrafında batıdan doğuya doğru döner. Dünya’nın bir tam dönüşü 24 saat sürer. Bu süreye bir gün adı verilir.
Dünya’nın ekseni etrafındaki dönüşüne bağlı olarak iki türlü hız ortaya çıkar. Dünya’nın günlük hareketi esnasında birim zamanda aldığı yola çizgisel (dönüş) hız denir. Çizgisel hız Ekvator’dan kutuplara doğru azalır. Dünya’nın günlük hareketi esnasında birim zamanda oluşturduğu açıya da açısal hız denir. Dünya 24 saatte 360° döndüğünden üzerindeki tüm noktaların açısal hızları eşittir.
Dünya günlük hareketini batıdan doğuya doğru yapar. Bu yönlü hareketin sonuçları şunlardır:
• Doğuda yerel saat ileride, batıda ise geridedir.
• Güneş doğuda erken doğar, erken batar; batıda ise geç doğar, geç batar.
• Sürekli rüzgârlar Kuzey Yarım Küre’de sağa, Güney Yarım Küre’de ise sola sapar.
Dünya’nın Günlük (Eksen) Hareketinin Sonuçları
• Gece ve gündüz birbirini takip eder.
• Güneş ışınlarının günlük geliş açıları değişir.
• Günlük sıcaklık farkları meydana gelir. Bunun sonucunda;
– Fiziksel çözülme oluşur.
– Günlük basınç farkları oluşur.
– Meltem rüzgârları oluşur.
• Merkez kaç kuvveti meydana gelir. Bunun sonucunda;
– Sürekli rüzgârların (Alize, Batı, Kutup) yönlerinde sapmalar meydana gelir.
– Okyanus akıntıları (Gulf – stream, Labrador, vs.) halkalar oluşturur ve yönlerinde sapmalar olur.
• Yerel saat farkları meydana gelir.
• Cisimlerin gün içindeki gölge uzunlukları değişir.
• Güneş doğuda erken doğar, batar ve batıda geç doğar, batar.
• Dinamik basınç kuşakları meydana gelir.
Cevap: Dünya'nın günlük hareketi, Dünya'nın manyetik alanının oluşumu, gelgitlerin oluşumu ve gökyüzündeki yıldızların hareketleri gibi birçok başka sonuca da neden olur.

Label:

--- TRUE LABEL: 0

In [1]:
import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("GPU yok. Runtime ayarlarından GPU açman gerekiyor.")

CUDA available: True
GPU: Tesla T4

In [2]:
!pip install transformers accelerate bitsandbytes sentencepiece pandas scikit-learn -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 20.2 MB/s eta 0:00:00

In [3]:
import os
import pandas as pd
import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

test_path = "data/processed/strategy_b/test.csv"
print("Test file exists:", os.path.exists(test_path))

CUDA available: True
GPU: Tesla T4
Test file exists: False

In [6]:
import os

test_path = "/data/processed/strategy_b/test.csv"
print("Test file exists:", os.path.exists(test_path))

Test file exists: True

In [7]:
import pandas as pd
import os

test_path = "/data/processed/strategy_b/test.csv"

print("Test file exists:", os.path.exists(test_path))

test_df = pd.read_csv(test_path)

print("Shape:", test_df.shape)
print("Columns:", test_df.columns.tolist())
print("\nLabel distribution:")
print(test_df["label"].value_counts().sort_index())

Test file exists: True
Shape: (1447, 8)
Columns: ['input_text', 'label', 'Score', 'soru', 'context', 'cevap', 'kaynak', 'veri türü']

Label distribution:
label
0    885
1    562
Name: count, dtype: int64

In [8]:
sample_label_0 = test_df[test_df["label"] == 0].sample(n=10, random_state=42)
sample_label_1 = test_df[test_df["label"] == 1].sample(n=10, random_state=42)

zero_shot_sample = pd.concat([sample_label_0, sample_label_1])
zero_shot_sample = zero_shot_sample.sample(frac=1, random_state=42).reset_index(drop=True)

print("Sample shape:", zero_shot_sample.shape)
print("Sample label distribution:")
print(zero_shot_sample["label"].value_counts().sort_index())

Sample shape: (20, 8)
Sample label distribution:
label
0    10
1    10
Name: count, dtype: int64

In [9]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.float16
)

model.eval()

print("Model loaded:", model_id)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Model loaded: Qwen/Qwen2.5-1.5B-Instruct

In [11]:
def create_zero_shot_prompt(input_text):
    prompt = f"""
You are evaluating the quality of a Turkish open-ended student answer.

Your task is to classify the answer into one of two labels:

0 = low quality answer
1 = high quality answer

Consider whether the answer is relevant to the question, consistent with the context, and sufficiently explanatory.

Return only one number: 0 or 1.

Input:
{input_text}

Label:
"""
    return prompt.strip()

In [12]:
example = zero_shot_sample.iloc[0]
example_prompt = create_zero_shot_prompt(example["input_text"])

print(example_prompt[:2000])
print("\nTrue label:", example["label"])

You are evaluating the quality of a Turkish open-ended student answer.

Your task is to classify the answer into one of two labels:

0 = low quality answer
1 = high quality answer

Consider whether the answer is relevant to the question, consistent with the context, and sufficiently explanatory.

Return only one number: 0 or 1.

Input:
Soru: Dünya'nın günlük hareketi ile ilgili başka hangi sonuçlar vardır?
Bağlam: Dünya’nın Günlük (Eksen) Hareketi
Dünya, kuzey ve güney kutup noktalarından geçtiği varsayılan yer ekseni etrafında batıdan doğuya doğru döner. Dünya’nın bir tam dönüşü 24 saat sürer. Bu süreye bir gün adı verilir.
Dünya’nın ekseni etrafındaki dönüşüne bağlı olarak iki türlü hız ortaya çıkar. Dünya’nın günlük hareketi esnasında birim zamanda aldığı yola çizgisel (dönüş) hız denir. Çizgisel hız Ekvator’dan kutuplara doğru azalır. Dünya’nın günlük hareketi esnasında birim zamanda oluşturduğu açıya da açısal hız denir. Dünya 24 saatte 360° döndüğünden üzerindeki tüm noktaların açısal hızları eşittir.
Dünya günlük hareketini batıdan doğuya doğru yapar. Bu yönlü hareketin sonuçları şunlardır:
• Doğuda yerel saat ileride, batıda ise geridedir.
• Güneş doğuda erken doğar, erken batar; batıda ise geç doğar, geç batar.
• Sürekli rüzgârlar Kuzey Yarım Küre’de sağa, Güney Yarım Küre’de ise sola sapar.
Dünya’nın Günlük (Eksen) Hareketinin Sonuçları
• Gece ve gündüz birbirini takip eder.
• Güneş ışınlarının günlük geliş açıları değişir.
• Günlük sıcaklık farkları meydana gelir. Bunun sonucunda;
– Fiziksel çözülme oluşur.
– Günlük basınç farkları oluşur.
– Meltem rüzgârları oluşur.
• Merkez kaç kuvveti meydana gelir. Bunun sonucunda;
– Sürekli rüzgârların (Alize, Batı, Kutup) yönlerinde sapmalar meydana gelir.
– Okyanus akıntıları (Gulf – stream, Labrador, vs.) halkalar oluşturur ve yönlerinde sapmalar olur.
• Yerel saat farkları meydana gelir.
• Cisimlerin gün içindeki gölge uzunlukları değişir.
• Güneş doğuda erken doğar, batar ve batıda geç doğar,

True label: 0

In [13]:
def generate_prediction(prompt, max_new_tokens=5):
    messages = [
        {"role": "user", "content": prompt}
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            temperature=0.0,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_ids = outputs[0][inputs["input_ids"].shape[-1]:]
    response = tokenizer.decode(generated_ids, skip_special_tokens=True)

    return response.strip()

In [14]:
response = generate_prediction(example_prompt)

print("Model response:", repr(response))
print("True label:", example["label"])

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Model response: '1'
True label: 0

In [15]:
def generate_prediction(prompt, max_new_tokens=5):
    messages = [
        {"role": "user", "content": prompt}
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_ids = outputs[0][inputs["input_ids"].shape[-1]:]
    response = tokenizer.decode(generated_ids, skip_special_tokens=True)

    return response.strip()


def parse_prediction(response):
    response = str(response).strip()

    if response.startswith("0"):
        return 0
    elif response.startswith("1"):
        return 1
    elif "0" in response and "1" not in response:
        return 0
    elif "1" in response and "0" not in response:
        return 1
    else:
        return None

In [16]:
response = generate_prediction(example_prompt)
parsed = parse_prediction(response)

print("Raw response:", repr(response))
print("Parsed prediction:", parsed)
print("True label:", example["label"])

Raw response: '1'
Parsed prediction: 1
True label: 0

In [17]:
predictions = []
raw_responses = []

for idx, row in zero_shot_sample.iterrows():
    prompt = create_zero_shot_prompt(row["input_text"])
    response = generate_prediction(prompt)
    pred = parse_prediction(response)

    raw_responses.append(response)
    predictions.append(pred)

    print(f"Example {idx+1}/20")
    print("True label:", row["label"])
    print("Raw response:", repr(response))
    print("Parsed prediction:", pred)
    print("-" * 40)

zero_shot_sample_results = zero_shot_sample.copy()
zero_shot_sample_results["raw_response"] = raw_responses
zero_shot_sample_results["prediction"] = predictions

Example 1/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 2/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 3/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 4/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 5/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 6/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 7/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 8/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 9/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 10/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 11/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 12/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 13/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 14/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 15/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 16/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 17/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 18/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 19/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 20/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------

In [18]:
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

y_true_sample = zero_shot_sample_results["label"]
y_pred_sample = zero_shot_sample_results["prediction"]

sample_accuracy = accuracy_score(y_true_sample, y_pred_sample)
sample_macro_f1 = f1_score(y_true_sample, y_pred_sample, average="macro", zero_division=0)
sample_weighted_f1 = f1_score(y_true_sample, y_pred_sample, average="weighted", zero_division=0)

print("Qwen2.5-1.5B-Instruct Zero-Shot Sample Results")
print("Accuracy:", sample_accuracy)
print("Macro F1:", sample_macro_f1)
print("Weighted F1:", sample_weighted_f1)

print("\nConfusion Matrix:")
print(confusion_matrix(y_true_sample, y_pred_sample))

print("\nClassification Report:")
print(classification_report(y_true_sample, y_pred_sample, zero_division=0))

Qwen2.5-1.5B-Instruct Zero-Shot Sample Results
Accuracy: 0.5
Macro F1: 0.3333333333333333
Weighted F1: 0.3333333333333333

Confusion Matrix:
[[ 0 10]
 [ 0 10]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.50      1.00      0.67        10

    accuracy                           0.50        20
   macro avg       0.25      0.50      0.33        20
weighted avg       0.25      0.50      0.33        20

In [19]:
def create_zero_shot_prompt_v2(input_text):
    prompt = f"""
You are evaluating a Turkish open-ended student answer.

Classify the answer using the following strict rule:

0 = acceptable or weak answer. The answer may be partially correct, generic, incomplete, weakly explained, or not fully grounded in the context.
1 = very high-quality answer. The answer must be clearly relevant, accurate, sufficiently detailed, and well grounded in the given context.

Important:
Most acceptable answers should be labeled 0.
Use label 1 only when the answer is clearly strong and complete.

Return only one number: 0 or 1.

Input:
{input_text}

Label:
"""
    return prompt.strip()

In [20]:
predictions_v2 = []
raw_responses_v2 = []

for idx, row in zero_shot_sample.iterrows():
    prompt = create_zero_shot_prompt_v2(row["input_text"])
    response = generate_prediction(prompt)
    pred = parse_prediction(response)

    raw_responses_v2.append(response)
    predictions_v2.append(pred)

    print(f"Example {idx+1}/20")
    print("True label:", row["label"])
    print("Raw response:", repr(response))
    print("Parsed prediction:", pred)
    print("-" * 40)

zero_shot_sample_results_v2 = zero_shot_sample.copy()
zero_shot_sample_results_v2["raw_response"] = raw_responses_v2
zero_shot_sample_results_v2["prediction"] = predictions_v2

Example 1/20
True label: 0
Raw response: '0'
Parsed prediction: 0
----------------------------------------
Example 2/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 3/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 4/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 5/20
True label: 0
Raw response: '0'
Parsed prediction: 0
----------------------------------------
Example 6/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 7/20
True label: 1
Raw response: '0'
Parsed prediction: 0
----------------------------------------
Example 8/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 9/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 10/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 11/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 12/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 13/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 14/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 15/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 16/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 17/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 18/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 19/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 20/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------

In [21]:
y_true_sample_v2 = zero_shot_sample_results_v2["label"]
y_pred_sample_v2 = zero_shot_sample_results_v2["prediction"]

sample_accuracy_v2 = accuracy_score(y_true_sample_v2, y_pred_sample_v2)
sample_macro_f1_v2 = f1_score(y_true_sample_v2, y_pred_sample_v2, average="macro", zero_division=0)
sample_weighted_f1_v2 = f1_score(y_true_sample_v2, y_pred_sample_v2, average="weighted", zero_division=0)

print("Qwen2.5-1.5B-Instruct Zero-Shot Sample Results - Prompt v2")
print("Accuracy:", sample_accuracy_v2)
print("Macro F1:", sample_macro_f1_v2)
print("Weighted F1:", sample_weighted_f1_v2)

print("\nConfusion Matrix:")
print(confusion_matrix(y_true_sample_v2, y_pred_sample_v2))

print("\nClassification Report:")
print(classification_report(y_true_sample_v2, y_pred_sample_v2, zero_division=0))

Qwen2.5-1.5B-Instruct Zero-Shot Sample Results - Prompt v2
Accuracy: 0.55
Macro F1: 0.48717948717948717
Weighted F1: 0.4871794871794871

Confusion Matrix:
[[2 8]
 [1 9]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.20      0.31        10
           1       0.53      0.90      0.67        10

    accuracy                           0.55        20
   macro avg       0.60      0.55      0.49        20
weighted avg       0.60      0.55      0.49        20

In [22]:
sample_100_label_0 = test_df[test_df["label"] == 0].sample(n=50, random_state=42)
sample_100_label_1 = test_df[test_df["label"] == 1].sample(n=50, random_state=42)

zero_shot_sample_100 = pd.concat([sample_100_label_0, sample_100_label_1])
zero_shot_sample_100 = zero_shot_sample_100.sample(frac=1, random_state=42).reset_index(drop=True)

print("Sample shape:", zero_shot_sample_100.shape)
print("Sample label distribution:")
print(zero_shot_sample_100["label"].value_counts().sort_index())

Sample shape: (100, 8)
Sample label distribution:
label
0    50
1    50
Name: count, dtype: int64

In [23]:
predictions_100_v2 = []
raw_responses_100_v2 = []

for idx, row in zero_shot_sample_100.iterrows():
    prompt = create_zero_shot_prompt_v2(row["input_text"])
    response = generate_prediction(prompt)
    pred = parse_prediction(response)

    raw_responses_100_v2.append(response)
    predictions_100_v2.append(pred)

    if (idx + 1) % 10 == 0:
        print(f"Processed {idx + 1}/100")

zero_shot_sample_100_results_v2 = zero_shot_sample_100.copy()
zero_shot_sample_100_results_v2["raw_response"] = raw_responses_100_v2
zero_shot_sample_100_results_v2["prediction"] = predictions_100_v2

print("Done.")

Processed 10/100
Processed 20/100
Processed 30/100
Processed 40/100
Processed 50/100
Processed 60/100
Processed 70/100
Processed 80/100
Processed 90/100
Processed 100/100
Done.

In [24]:
y_true_100_v2 = zero_shot_sample_100_results_v2["label"]
y_pred_100_v2 = zero_shot_sample_100_results_v2["prediction"]

accuracy_100_v2 = accuracy_score(y_true_100_v2, y_pred_100_v2)
macro_f1_100_v2 = f1_score(y_true_100_v2, y_pred_100_v2, average="macro", zero_division=0)
weighted_f1_100_v2 = f1_score(y_true_100_v2, y_pred_100_v2, average="weighted", zero_division=0)

print("Qwen2.5-1.5B-Instruct Zero-Shot Results - 100 Sample - Prompt v2")
print("Accuracy:", accuracy_100_v2)
print("Macro F1:", macro_f1_100_v2)
print("Weighted F1:", weighted_f1_100_v2)

print("\nConfusion Matrix:")
print(confusion_matrix(y_true_100_v2, y_pred_100_v2))

print("\nClassification Report:")
print(classification_report(y_true_100_v2, y_pred_100_v2, zero_division=0))

Qwen2.5-1.5B-Instruct Zero-Shot Results - 100 Sample - Prompt v2
Accuracy: 0.52
Macro F1: 0.43899018232819076
Weighted F1: 0.43899018232819076

Confusion Matrix:
[[ 7 43]
 [ 5 45]]

Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.14      0.23        50
           1       0.51      0.90      0.65        50

    accuracy                           0.52       100
   macro avg       0.55      0.52      0.44       100
weighted avg       0.55      0.52      0.44       100

In [25]:
def create_zero_shot_prompt_v3(input_text):
    prompt = f"""
You are grading a Turkish open-ended student answer.

Use the following binary grading rule:

0 = not high-quality.
Choose 0 if the answer is only partially correct, too general, weakly explained, incomplete, contains unsupported claims, or does not fully use the given context.

1 = high-quality.
Choose 1 only if the answer is clearly correct, complete, well explained, directly relevant to the question, and well supported by the context.

Important rules:
- Do not give 1 just because the answer is fluent or long.
- If you are unsure, choose 0.
- Be strict. Label 1 should be reserved for very strong answers.

Return only one number: 0 or 1.

Input:
{input_text}

Label:
"""
    return prompt.strip()

In [26]:
predictions_20_v3 = []
raw_responses_20_v3 = []

for idx, row in zero_shot_sample.iterrows():
    prompt = create_zero_shot_prompt_v3(row["input_text"])
    response = generate_prediction(prompt)
    pred = parse_prediction(response)

    raw_responses_20_v3.append(response)
    predictions_20_v3.append(pred)

    print(f"Example {idx+1}/20")
    print("True label:", row["label"])
    print("Raw response:", repr(response))
    print("Parsed prediction:", pred)
    print("-" * 40)

zero_shot_sample_results_v3 = zero_shot_sample.copy()
zero_shot_sample_results_v3["raw_response"] = raw_responses_20_v3
zero_shot_sample_results_v3["prediction"] = predictions_20_v3

Example 1/20
True label: 0
Raw response: '0'
Parsed prediction: 0
----------------------------------------
Example 2/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 3/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 4/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 5/20
True label: 0
Raw response: '0'
Parsed prediction: 0
----------------------------------------
Example 6/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 7/20
True label: 1
Raw response: '0'
Parsed prediction: 0
----------------------------------------
Example 8/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 9/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 10/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 11/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 12/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 13/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 14/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 15/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 16/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 17/20
True label: 0
Raw response: '0'
Parsed prediction: 0
----------------------------------------
Example 18/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 19/20
True label: 1
Raw response: '1'
Parsed prediction: 1
----------------------------------------
Example 20/20
True label: 0
Raw response: '1'
Parsed prediction: 1
----------------------------------------

In [27]:
y_true_20_v3 = zero_shot_sample_results_v3["label"]
y_pred_20_v3 = zero_shot_sample_results_v3["prediction"]

accuracy_20_v3 = accuracy_score(y_true_20_v3, y_pred_20_v3)
macro_f1_20_v3 = f1_score(y_true_20_v3, y_pred_20_v3, average="macro", zero_division=0)
weighted_f1_20_v3 = f1_score(y_true_20_v3, y_pred_20_v3, average="weighted", zero_division=0)

print("Qwen2.5-1.5B-Instruct Zero-Shot Results - 20 Sample - Prompt v3")
print("Accuracy:", accuracy_20_v3)
print("Macro F1:", macro_f1_20_v3)
print("Weighted F1:", weighted_f1_20_v3)

print("\nConfusion Matrix:")
print(confusion_matrix(y_true_20_v3, y_pred_20_v3))

print("\nClassification Report:")
print(classification_report(y_true_20_v3, y_pred_20_v3, zero_division=0))

Qwen2.5-1.5B-Instruct Zero-Shot Results - 20 Sample - Prompt v3
Accuracy: 0.6
Macro F1: 0.5604395604395604
Weighted F1: 0.5604395604395604

Confusion Matrix:
[[3 7]
 [1 9]]

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.30      0.43        10
           1       0.56      0.90      0.69        10

    accuracy                           0.60        20
   macro avg       0.66      0.60      0.56        20
weighted avg       0.66      0.60      0.56        20

In [28]:
predictions_100_v3 = []
raw_responses_100_v3 = []

for idx, row in zero_shot_sample_100.iterrows():
    prompt = create_zero_shot_prompt_v3(row["input_text"])
    response = generate_prediction(prompt)
    pred = parse_prediction(response)

    raw_responses_100_v3.append(response)
    predictions_100_v3.append(pred)

    if (idx + 1) % 10 == 0:
        print(f"Processed {idx + 1}/100")

zero_shot_sample_100_results_v3 = zero_shot_sample_100.copy()
zero_shot_sample_100_results_v3["raw_response"] = raw_responses_100_v3
zero_shot_sample_100_results_v3["prediction"] = predictions_100_v3

print("Done.")

Processed 10/100
Processed 20/100
Processed 30/100
Processed 40/100
Processed 50/100
Processed 60/100
Processed 70/100
Processed 80/100
Processed 90/100
Processed 100/100
Done.

In [29]:
y_true_100_v3 = zero_shot_sample_100_results_v3["label"]
y_pred_100_v3 = zero_shot_sample_100_results_v3["prediction"]

accuracy_100_v3 = accuracy_score(y_true_100_v3, y_pred_100_v3)
macro_f1_100_v3 = f1_score(y_true_100_v3, y_pred_100_v3, average="macro", zero_division=0)
weighted_f1_100_v3 = f1_score(y_true_100_v3, y_pred_100_v3, average="weighted", zero_division=0)

print("Qwen2.5-1.5B-Instruct Zero-Shot Results - 100 Sample - Prompt v3")
print("Accuracy:", accuracy_100_v3)
print("Macro F1:", macro_f1_100_v3)
print("Weighted F1:", weighted_f1_100_v3)

print("\nConfusion Matrix:")
print(confusion_matrix(y_true_100_v3, y_pred_100_v3))

print("\nClassification Report:")
print(classification_report(y_true_100_v3, y_pred_100_v3, zero_division=0))

Qwen2.5-1.5B-Instruct Zero-Shot Results - 100 Sample - Prompt v3
Accuracy: 0.57
Macro F1: 0.5242836596968692
Weighted F1: 0.5242836596968692

Confusion Matrix:
[[13 37]
 [ 6 44]]

Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.26      0.38        50
           1       0.54      0.88      0.67        50

    accuracy                           0.57       100
   macro avg       0.61      0.57      0.52       100
weighted avg       0.61      0.57      0.52       100

In [30]:
import pandas as pd
import os

zero_shot_prompt_comparison = pd.DataFrame([
    {
        "model": "Qwen2.5-1.5B-Instruct",
        "evaluation_type": "zero_shot_sample",
        "sample_size": 20,
        "prompt_version": "v1",
        "accuracy": sample_accuracy,
        "macro_f1": sample_macro_f1,
        "weighted_f1": sample_weighted_f1,
        "notes": "Initial prompt; model predicted label 1 for all examples."
    },
    {
        "model": "Qwen2.5-1.5B-Instruct",
        "evaluation_type": "zero_shot_sample",
        "sample_size": 20,
        "prompt_version": "v2",
        "accuracy": sample_accuracy_v2,
        "macro_f1": sample_macro_f1_v2,
        "weighted_f1": sample_weighted_f1_v2,
        "notes": "Stricter prompt; reduced but did not remove label 1 bias."
    },
    {
        "model": "Qwen2.5-1.5B-Instruct",
        "evaluation_type": "zero_shot_sample",
        "sample_size": 100,
        "prompt_version": "v2",
        "accuracy": accuracy_100_v2,
        "macro_f1": macro_f1_100_v2,
        "weighted_f1": weighted_f1_100_v2,
        "notes": "Balanced 100-sample evaluation with prompt v2."
    },
    {
        "model": "Qwen2.5-1.5B-Instruct",
        "evaluation_type": "zero_shot_sample",
        "sample_size": 20,
        "prompt_version": "v3",
        "accuracy": accuracy_20_v3,
        "macro_f1": macro_f1_20_v3,
        "weighted_f1": weighted_f1_20_v3,
        "notes": "Strict prompt; better than v2 on 20-sample test."
    },
    {
        "model": "Qwen2.5-1.5B-Instruct",
        "evaluation_type": "zero_shot_sample",
        "sample_size": 100,
        "prompt_version": "v3",
        "accuracy": accuracy_100_v3,
        "macro_f1": macro_f1_100_v3,
        "weighted_f1": weighted_f1_100_v3,
        "notes": "Best prompt so far; still biased toward label 1."
    }
])

zero_shot_prompt_comparison

,model,evaluation_type,sample_size,prompt_version,accuracy,macro_f1,weighted_f1,notes
0,Qwen2.5-1.5B-Instruct,zero_shot_sample,20,v1,0.50,0.333333,0.333333,Initial prompt; model predicted label 1 for al...
1,Qwen2.5-1.5B-Instruct,zero_shot_sample,20,v2,0.55,0.487179,0.487179,Stricter prompt; reduced but did not remove la...
2,Qwen2.5-1.5B-Instruct,zero_shot_sample,100,v2,0.52,0.438990,0.438990,Balanced 100-sample evaluation with prompt v2.
3,Qwen2.5-1.5B-Instruct,zero_shot_sample,20,v3,0.60,0.560440,0.560440,Strict prompt; better than v2 on 20-sample test.
4,Qwen2.5-1.5B-Instruct,zero_shot_sample,100,v3,0.57,0.524284,0.524284,Best prompt so far; still biased toward label 1.

In [31]:
os.makedirs("/outputs/tables", exist_ok=True)

zero_shot_prompt_comparison.to_csv(
    "/outputs/tables/qwen_zero_shot_prompt_comparison.csv",
    index=False
)

print("Saved:")
print("/outputs/tables/qwen_zero_shot_prompt_comparison.csv")

Saved:
/outputs/tables/qwen_zero_shot_prompt_comparison.csv

In [32]:
print(os.path.exists("/outputs/tables/qwen_zero_shot_prompt_comparison.csv"))

True

In [33]:
qwen_zero_shot_100_predictions = zero_shot_sample_100_results_v3[[
    "input_text",
    "label",
    "Score",
    "soru",
    "cevap",
    "raw_response",
    "prediction"
]].copy()

qwen_zero_shot_100_predictions["model"] = "Qwen2.5-1.5B-Instruct"
qwen_zero_shot_100_predictions["prompt_version"] = "v3"

qwen_zero_shot_100_predictions.to_csv(
    "/outputs/tables/qwen_zero_shot_100_sample_predictions_v3.csv",
    index=False
)

print("Saved:")
print("/outputs/tables/qwen_zero_shot_100_sample_predictions_v3.csv")
print("Shape:", qwen_zero_shot_100_predictions.shape)

Saved:
/outputs/tables/qwen_zero_shot_100_sample_predictions_v3.csv
Shape: (100, 9)

In [34]:
print(os.path.exists("/outputs/tables/qwen_zero_shot_100_sample_predictions_v3.csv"))

True